[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn -N install"]

[phases.build]
cmds = ["cd backend/program-service && mvn clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar backend/program-service/target/program-service-1.0.0-SNAPSHOT.jar"
